

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryCommon'),
                       bld.Path('Code/CryEngine/CryAction')],
		
		# is defined for windows only.
        win_uselib      = ['HYPEREALVR'],
        win_file_list   = ['hyperealvr_win.waf_files'],
    )